version: '3'
services:
  ngrok:
    image: wernight/ngrok
    command: ngrok http agent:3000 --log stdout

  requester:
    image: didcomm-requester-with-ngrok
    build:
      context: ..
      dockerfile: ./demo/Dockerfile.ngrok
    environment:
      - NGROK_NAME=ngrok
    depends_on:
      - ngrok
    command: aca-py start --arg-file default.yml --plugin didcomm_resolver.role.requester --log-level debug --invite
