version: '3'
services:
  resolver:
    image: universal-resolver
    build:
      context: ./uniresolver
      dockerfile: Dockerfile
    command: start --arg-file config.yml -e http://resolver:8180 --log-level debug

  requester:
    image: didcomm-requester
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    command: start --arg-file default.yml --plugin didcomm_resolver.role.requester -e http://requester:3000 --log-level debug

  demo:
      container_name: juggernaut
      build:
        context: runner
        dockerfile: Dockerfile
      environment:
        - WAIT_BEFORE_HOSTS=3
        - WAIT_HOSTS=requester:3000
        - WAIT_HOSTS_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
      depends_on:
        - resolver
        - requester
