name: Test Actions
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit tests
        run: pytest --cov-report term-missing --cov
      - name: intigration tests
        run: docker-compose run tests && docker-compose stop
